### ISSUE TITLE
Game Mario

### ISSUE THREAD

**Issue by Jovancito7** [Luxon98/Mario#1]

**Comment by ArsalanS33d** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\MSVCRTD.lib(exe_main.obj)	1		
Error	LNK2019	unresolved external symbol SDL_GetKeyboardState referenced in function "void __cdecl handleMenu(bool *,int *,int *,class Screen &)" (?handleMenu@@YAXPEA_NPEAH1AEAVScreen@@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\GameFunctions.obj	1		
Error	LNK2019	unresolved external symbol SDL_PollEvent referenced in function "void __cdecl handleMenu(bool *,int *,int *,class Screen &)" (?handleMenu@@YAXPEA_NPEAH1AEAVScreen@@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\GameFunctions.obj	1		
Error	LNK2001	unresolved external symbol SDL_PollEvent	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_MapRGB referenced in function "private: void __cdecl Screen::setBlackBackground(void)" (?setBlackBackground@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_CreateRGBSurface referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_FreeSurface referenced in function "public: __cdecl Screen::~Screen(void)" (??1Screen@@QEAA@XZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2001	unresolved external symbol SDL_FreeSurface	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol SDL_FillRect referenced in function "private: void __cdecl Screen::setBlackBackground(void)" (?setBlackBackground@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_SetWindowTitle referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_DestroyWindow referenced in function "private: void __cdecl Screen::closeGUI(void)" (?closeGUI@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_ShowCursor referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_SetHint referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_CreateWindowAndRenderer referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_CreateTexture referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_UpdateTexture referenced in function "public: void __cdecl Screen::updateView(void)" (?updateView@Screen@@QEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_RenderSetLogicalSize referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_SetRenderDrawColor referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_RenderCopy referenced in function "public: void __cdecl Screen::updateView(void)" (?updateView@Screen@@QEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_RenderPresent referenced in function "public: void __cdecl Screen::updateView(void)" (?updateView@Screen@@QEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_DestroyTexture referenced in function "private: void __cdecl Screen::closeGUI(void)" (?closeGUI@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_DestroyRenderer referenced in function "private: void __cdecl Screen::closeGUI(void)" (?closeGUI@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_Init referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_Quit referenced in function "private: void __cdecl Screen::closeGUI(void)" (?closeGUI@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol IMG_Init referenced in function "private: int __cdecl Screen::initGUI(void)" (?initGUI@Screen@@AEAAHXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol IMG_Quit referenced in function "private: void __cdecl Screen::closeGUI(void)" (?closeGUI@Screen@@AEAAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\Screen.obj	1		
Error	LNK2019	unresolved external symbol SDL_RWFromFile referenced in function "struct SDL_Surface * __cdecl loadBMP(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?loadBMP@@YAPEAUSDL_Surface@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2001	unresolved external symbol SDL_RWFromFile	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol SDL_LoadBMP_RW referenced in function "struct SDL_Surface * __cdecl loadBMP(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?loadBMP@@YAPEAUSDL_Surface@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol SDL_ConvertSurface referenced in function "struct SDL_Surface * __cdecl loadPNG(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct SDL_Surface *)" (?loadPNG@@YAPEAUSDL_Surface@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU1@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol SDL_UpperBlit referenced in function "void __cdecl drawSurface(struct SDL_Surface *,struct SDL_Surface *,int,int)" (?drawSurface@@YAXPEAUSDL_Surface@@0HH@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol SDL_ShowSimpleMessageBox referenced in function "void __cdecl showFileErrorWindow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?showFileErrorWindow@@YAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol IMG_Load referenced in function "struct SDL_Surface * __cdecl loadPNG(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct SDL_Surface *)" (?loadPNG@@YAPEAUSDL_Surface@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAU1@@Z)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SDL_Utility.obj	1		
Error	LNK2019	unresolved external symbol Mix_Quit referenced in function "public: static void __cdecl SoundController::closeSoundController(void)" (?closeSoundController@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_OpenAudio referenced in function "public: static bool __cdecl SoundController::initSoundMixer(void)" (?initSoundMixer@SoundController@@SA_NXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_LoadWAV_RW referenced in function "private: static void __cdecl SoundController::loadSoundEffects(void)" (?loadSoundEffects@SoundController@@CAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_LoadMUS referenced in function "private: static void __cdecl SoundController::loadBackgroundTracks(void)" (?loadBackgroundTracks@SoundController@@CAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_FreeChunk referenced in function "public: static void __cdecl SoundController::closeSoundController(void)" (?closeSoundController@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_FreeMusic referenced in function "public: static void __cdecl SoundController::closeSoundController(void)" (?closeSoundController@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_PlayChannelTimed referenced in function "public: static void __cdecl SoundController::playBlockDestroyedEffect(void)" (?playBlockDestroyedEffect@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_PlayMusic referenced in function "public: static void __cdecl SoundController::playBackgroundMusic(void)" (?playBackgroundMusic@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_VolumeMusic referenced in function "public: static void __cdecl SoundController::playBackgroundMusic(void)" (?playBackgroundMusic@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1		
Error	LNK2019	unresolved external symbol Mix_HaltMusic referenced in function "public: static void __cdecl SoundController::stopMusic(void)" (?stopMusic@SoundController@@SAXXZ)	Mario	C:\C1-Assignment\Super-Mario-Bros-game-master\Mario\SoundController.obj	1
